# ===============================
# azure-ui.yml — UI Pipeline
# ===============================
trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

variables:
  azureSubscription: "Azure for Students" # Replace with your Azure connection name
  appName: "InkSync-UI" # Name of your Azure App Service for the UI
  packageDir: "ui" # Directory containing the UI project

steps:
  - task: UseNode@1
    inputs:
      version: "18.x"

  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - script: |
      cd $(packageDir)
      npm install
    displayName: "Install dependencies"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(packageDir)"
      includeRootFolder: false
      archiveType: zip
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(appName).zip"
      replaceExistingArchive: true
    displayName: "Archive UI files"

  - task: AzureWebApp@1
    inputs:
      azureSubscription: "$(azureSubscription)"
      appName: "$(appName)"
      package: "$(Build.ArtifactStagingDirectory)/$(appName).zip"
    displayName: "Deploy to Azure App Service (UI)"
