name: Deploy UI Service

on:
  push:
    branches: [main]
    paths:
      - "ui/**" # Only run if files under ui/ changed
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ui # Run steps in the ui/ subfolder

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # - name: Run tests (optional)
      #   run: npm test

      - name: Deploy to Azure Web App (InkSync-UI)
        uses: azure/webapps-deploy@v3
        with:
          app-name: "InkSync-UI" # Azure App Service name for the UI
          publish-profile: ${{ secrets.INKSYNC_UI_PUBLISH_PROFILE }}
          package: "."
